spring.application.name=${APP_NAME}

server.port=${SERVER_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

jwt.secret.key = ${JWT_SECRET_KEY}

server.servlet.context-path=${API_CONTEXT_PATH}

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS_ENABLE}
spring.mail.protocol=${SMTP_PROTOCOL}
spring.mail.properties.mail.smtp.from=${SMTP_MAIL_FROM}

spring.autoconfigure.exclude=${AUTOCONFIGURE_EXCLUDE}